### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by windyrobin** [tj/term-canvas#1]
v0.5.9

home/wb-zhanyanming/vcanvas/lib/context2d.js:81
  var hr = Array(w + 1).join('-');
           ^
RangeError: Invalid array length
    at Context2d.strokeRect (/home/wb-zhanyanming/vcanvas/lib/context2d.js:81:12)
    at Timer.<anonymous> (/home/wb-zhanyanming/vcanvas/examples/rects.js:34:7)
    at Timer.ontimeout (timers_uv.js:208:14)

could you pleas add a statement of which version would be supported?

**Comment by tj** [comment]
im testing with 0.4.x

**Comment by tj** [comment]
fixed the examples for 0.6.x
